fos_rest:
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
            - { path: ^/product, prefer_extension: true, fallback_format: html, priorities: [ json, html ] }
            - { path: ^/random, prefer_extension: true, fallback_format: html, priorities: [ json, html ] }
